variable "instance_type" { default =  "t3a.micro"}
variable "sg_ids" { default = "" }
variable "subnet_id" { default = "" }
variable "user_data" { default = "" }
variable "iam_instance_profile" { default = "" }
variable "volume_size" { default = "" }
variable "instance_name" { default = "" }
variable "environment" { default = "" }
variable "os" { default = "" }
variable "key_name" { default = "" }